### ISSUE TITLE
Auto Detected 2048 x 1440, Not Found set to 1280 x 720

### ISSUE THREAD

**Issue by VasTShadowZz** [Paladiex/Palbot#3]
Screen Resalushen (xd) not supported Nexus 9

**Comment by auto-config** [comment]
I'm sorry to say but this is intended. The only supported resolution is 1920x1080; although being able to support any resolution would be nice it would require remapping regions, locations, and implementing a set of images for each one. Aside of just the varying physical screen sizes of each android capable phone there is also soft keys and navigation bars which change the available screen resolution where the game would be rendered. This means there could be at least a few hundred screen resolutions that would need to be mapped and have it's own image folder in the script. This creates a large amount of unnecessary work.

For these reasons, the script writer decided to focus on only 1920x1080. For anyone who's devices are not that resolution the script writer suggested to use Nox and set the resolution to 1920x1080.

**Comment by mblom122** [comment]
How do you install this? What programs is needed?
