### ISSUE TITLE
stop on start

### ISSUE THREAD

**Issue by kangaroo011** [Paladiex/Palbot#9]
Runtime error: java.io.IOException:
Can;t open /sdcard/Ankulua/palbot-master/1920x1080/Prepare.png
stack traceback:
[C]: in function 'exists'
/sdcard/Ankulua/Palbot-master/Palbot.lua:4289: in main chunk

**Comment by kangaroo011** [comment]
Replace palbot dir in anklua and issue is fixed. Thanks for best bot :)

**Comment by digaomatias** [comment]
Yep. That happened because after updating you didn't have the png file. Usually, after an update that includes image, you can just run the imageuploader.lua script and it will download all images again. Of course just replacing the dir works. Thanks!
